# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 9a0b9beea8e0b7eebfdd2ad23c7ea68aa590d215a64981a6ba38e15068cfd4b89afa8eb89953f6cad25373c9f5163218410483e6190e67d82154643778e27482

test:
  secret_key_base: ebd40dcf6cadec58426dbfdd124764bdb3302685cf70d5f9c50645a7986f9adeb1dcd68abfc4590c85c7acf49f882da2a5f972d09ba00025a3344ad040bc1397

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
